[package]
name = "ddragon"
version = "0.3.1"
edition = "2021"
license = "MIT"
description = "Library for pulling data from ddragon, with caching support."
homepage = "https://github.com/kade-robertson/ddragon"
repository = "https://github.com/kade-robertson/ddragon"
readme = "./README.md"
keywords = ["ddragon", "league-of-legends", "lol", "league", "legends"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacache-sync = { version = "11.0.0", optional = true }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91", optional = true }
thiserror = { version = "1.0.38", optional = true }
ureq = { version = "2.6.2", features = ["json"], optional = true }
url = { version = "2.3.1", optional = true }

[dev-dependencies]
mockito = "0.31.1"

[features]
default = ["sync", "local-cache"]
sync = ["dep:serde_json", "dep:thiserror", "dep:ureq", "dep:url"]
local-cache = ["sync", "dep:cacache-sync"]
