[package]
name = "ddragon"
version = "0.5.0"
edition = "2021"
license = "MIT"
description = "Library for pulling data from ddragon, with caching support."
homepage = "https://github.com/kade-robertson/ddragon"
repository = "https://github.com/kade-robertson/ddragon"
readme = "./README.md"
keywords = ["ddragon", "league-of-legends", "lol", "league", "legends"]
categories = ["api-bindings"]

[dependencies]
cacache-sync = { version = "11.0.0", optional = true }
http-cache-reqwest = { version = "0.5.2", optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }
reqwest-middleware = { version = "0.2.0", optional = true }
serde = { version = "1.0.152", features = ["derive"] }
thiserror = { version = "1.0.38", optional = true }
ureq = { version = "2.6.2", features = ["json"], optional = true }
url = { version = "2.3.1", optional = true }

[dev-dependencies]
mockito = "0.31.1"
tokio-test = "0.4.2"

[features]
default = ["sync"]
sync = ["dep:thiserror", "dep:url", "dep:ureq", "dep:cacache-sync"]
async = ["dep:thiserror", "dep:url", "dep:reqwest", "dep:reqwest-middleware", "dep:http-cache-reqwest"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]