[package]
name = "ddragon"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Library for pulling data from ddragon, with caching support."
homepage = "https://github.com/uggo-lol/ddragon"
repository = "https://github.com/uggo-lol/ddragon"
readme = "./README.md"
keywords = ["ddragon", "league-of-legends", "lol", "league", "legends"]
categories = ["api-bindings"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cacache = "10.0.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
ureq = { version = "2.6.2", features = ["json"] }
url = "2.3.1"

[dev-dependencies]
mockito = "0.31.1"
