on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

name: build-caches
jobs:
  build-cache:
    name: build rust caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        runner: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-

      - name: Install tools
        run: |
          cargo install --locked cargo-audit
          cargo install --locked cargo-outdated
          cargo install --locked cargo-msrv

      - name: Test (to build cache)
        run: |
          cargo test --all-features -- --test-threads 1
          cargo test --all-features --release -- --test-threads 1