on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '7 7 * * *'

name: health
jobs:
  test:
    name: health check (${{ runner.os }}, ${{ matrix.toolchain }}, ${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            features: --features sync,async,image
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            features: --features sync,async-rustls,image
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-apple-darwin
            runner: macos-latest
            features: --features sync,async,image
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Health Check
        run: cargo test --all-features --release -- --test health --nocapture