on:
  schedule:
    - cron: '7 7 * * *'

name: health
jobs:
  test:
    name: health check (${{ matrix.runner }}, ${{ matrix.toolchain }}, ${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            features: --features sync,async,image
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            features: --features sync,async-rustls,image
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-apple-darwin
            runner: macos-latest
            features: --features sync,async,image
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-

      - name: Health Check
        run: cargo test ${{ matrix.features }} --release -- --test health --nocapture