on:
  pull_request:
    branches: [ master ]

name: test
jobs:
  test:
    name: unit + integration tests (${{ runner.os }}, ${{ matrix.toolchain }}, ${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        toolchain: [1.63.0, stable, beta, nightly]
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            features: --features sync,async,image
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            features: --features sync,async-rustls,image
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
            features: --features sync,async,image
          - target: x86_64-apple-darwin
            runner: macos-latest
            features: --features sync,async,image
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
          components: rustfmt

      - name: Install tools
        run: |
          cargo install --locked cargo-audit
          cargo install --locked cargo-outdated
          cargo install --locked cargo-msrv
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: |
          cargo audit
          cargo outdated --exit-code 1
          cargo msrv --verify -- cargo check ${{ matrix.features }}

      - name: Test
        run: |
          cargo test ${{ matrix.features }} --lib -- --test-threads 1
          cargo test ${{ matrix.features }} --doc
          cargo test ${{ matrix.features }} --release -- --test health --nocapture