on:
  pull_request:
    branches: [ master ]

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

name: test
jobs:
  test:
    name: unit + integration tests (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt

      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-

      - name: Install tools
        run: |
          cargo install --locked cargo-audit
          cargo install --locked cargo-outdated
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: |
          cargo audit
          cargo outdated --exit-code 1

      - name: Test
        run: |
          cargo test --all-features --lib -- --test-threads 1
          cargo test --all-features --doc
          cargo test --all-features --release -- --test health --nocapture