on:
  pull_request:
    branches: [ master ]

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

name: test
jobs:
  test:
    name: unit + integration tests (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-

      - name: Install tools
        run: |
          cargo install --locked cargo-audit
          cargo install --locked cargo-outdated
      
      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: |
          cargo audit
          cargo outdated --exit-code 1

      - name: Test
        run: cargo test --all-features -- --test-threads 1 --nocapture